version: '3'
services:
  quiz-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/quiz_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8080
  postgres:
    image: "postgres:14"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_app
    volumes:
      - pg_backups:/var/backups
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"

volumes:
  pg_backups: