spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: validate
spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: admin
spring.datasource.driver-class-name: org.postgresql.Driver
#spring.jpa.show-sql: true

spring.freemarker:
  expose-request-attributes: true
  expose-session-attributes: true

upload.path:
  img: '/Users/i/IdeaProjects/QuizApp/img'
  imgPrefix: 'C:'
domain.name: 'http://localhost:8080'

spring.servlet.multipart.max-file-size: 1MB
spring.servlet.multipart.max-request-size: 1MB

spring.profiles.include:
  - mail
  - secret

default:
  fiveVariant:
    firstWeight: 0
    secondWeight: 0
    thirdWeight: 2
    fourthWeight: 3
    fifthWeight: 4
  yesOrNo:
    noWeight: 0
    yesWeight: 4
  ratio:
    yellow: 2
    red: 3