spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: quiz_app
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: changes

#management.endpoints.web.exposure.include: 'httptrace'
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
upload.path:
  img: '/Users/i/IdeaProjects/QuizApp/img'
  imgPrefix: 'C:'
domain.name: localhost:8082
server:
  port: 8082
#
logging:
  level:
    ROOT: INFO
#  file:
#    name: application.log