spring:
  jpa:
    show-sql: false
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: quiz_app
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: changes
  #jpa.show-sql: true

upload.path:
  img: '/Users/i/IdeaProjects/QuizApp/img'
  imgPrefix: 'C:'
domain.name: localhost:8080
#
#logging:
#  level:
#    ROOT: ERROR
#  file:
#    name: application.log