spring.freemarker:
  expose-request-attributes: true
  expose-session-attributes: true


spring.servlet.multipart.max-file-size: 1MB
spring.servlet.multipart.max-request-size: 1MB

spring.profiles.include:
  - mail
  - secret
  - main

default:
  fiveVariant:
    firstWeight: 0
    secondWeight: 0
    thirdWeight: 2
    fourthWeight: 3
    fifthWeight: 4
  yesOrNo:
    noWeight: 0
    yesWeight: 4
  ratio:
    yellow: 2
    red: 3